server:
  port: 5566

spring:
  application:
    name: fix-agent
  output.ansi.enabled: ALWAYS

workspace:
  path: /tmp/backendAgent

package-metadata:
  filter-engine:
    folder: FilterEngine
  core-engine:
    folder: bin
  config-folder:
    folder: config